修改 css 插入方式 & 修改 helper 编译脚本
mipengine/mip-components-webpack-helpers pull request #1
Opened 2019-01-22 07:07 UTC by clark-t

1. css 插入方式从 header.appendChild() 改为 header.insertBefore(style, header.firstChild)
2. 编译脚本去掉 babel
3. 编译脚本注入 babel-runtime-helper 的方式改为 rollup-plugin-replace 实现
4. 编译脚本不再生成中间产物 source.js 而是直接从 index.js 生成 dist
5. 生成产物 dist 不压缩

2019-03-08 03:05 UTC, clark-t commented
关联 ISSUE:
https://github.com/mipengine/mip2/issues/536

2019-03-15 08:51 UTC, zoumiaojiang requested changes

2019-03-15 08:51 UTC, zoumiaojiang commented on src/add-styles-client.js
> +  if (!hasDocument) {
这个 if 语句缩进有点问题

2019-03-15 08:51 UTC, zoumiaojiang commented on src/add-styles-client.js
> +export default function addStylesClient (parentId, list, _isProduction, _options) {
把这些函数注释都补充一下？不然别人看起来很难理解

2019-03-15 08:51 UTC, zoumiaojiang commented on src/add-styles-client.js
> +var hasDocument = typeof document !== 'undefined'
import 都用上了，是不是语法 es6 搞起来？

2019-03-15 08:51 UTC, zoumiaojiang commented on src/add-styles-client.js
> +      var parts = []
下面一坨 Array.map 感觉清楚点

2019-03-15 08:51 UTC, zoumiaojiang commented on lib/utils.js
> +function pathFormat (pathname) {
工具函数加点注释

2019-03-26 05:50 UTC, clark-t commented on src/add-styles-client.js
> +var hasDocument = typeof document !== 'undefined'
不能，这个不走 babel，只保留 esm 给 rollup 做资源管理

2019-03-26 05:50 UTC, clark-t commented on src/add-styles-client.js
> +      var parts = []
这个是 style-loader 的源码拷贝过来做修改的，不打算改的太多

2019-03-26 05:51 UTC, clark-t commented on src/add-styles-client.js
> +  if (!hasDocument) {
这个是 style-loader 源码拷贝过来做修改的，不打算改动太多

2019-03-26 05:51 UTC, clark-t commented on src/add-styles-client.js
> +export default function addStylesClient (parentId, list, _isProduction, _options) {
这个是 style-loader 的源码拷贝过来做修改的，不打算改的太多

2019-03-26 06:17 UTC, clark-t commented on lib/utils.js
> +function pathFormat (pathname) {
done

2019-03-26 06:21 UTC, zoumiaojiang approved these changes

2019-05-14 02:13 UTC, merged